apply plugin: 'com.android.application'

android {
    compileSdk 35

    signingConfigs {
        config {
            storeFile file('C:\\Git\\android_keystores\\base\\base.jks')
            keyAlias = 'base'
            keyPassword 'Base12345678@'
            storePassword 'Base12345678@'
        }
        debug {
            storeFile file('C:\\Git\\android_keystores\\base\\base.jks')
            keyAlias = 'base'
            keyPassword 'Base12345678@'
            storePassword 'Base12345678@'
        }
    }
    defaultConfig {
        applicationId "com.base.emuilauncherrestarter"
        minSdk 24
        targetSdk 35
        versionCode 1000
        versionName '1.0.0.0'
//        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
            signingConfig signingConfigs.config
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

static def releaseTime() {
    return new Date().format("ddMMyyyy", TimeZone.getTimeZone("UTC"))
}

android.applicationVariants.all {
    variant -> variant.outputs.all {
        outputFileName = "restarter_${variant.buildType.name}_v${variant.versionName}_${releaseTime()}.apk"
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
